name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  superclass:
    path: ../../superclass

dev_dependencies:
  build_runner: ^2.4.9
  lints: ^3.0.0
  superclass_generator:
    path: ..
  test: ^1.24.0
