name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  superclass:

dev_dependencies:
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.8.0
  lints: ^3.0.0
  superclass_generator:
    path: ..
  test: ^1.24.0
