name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  superclass:

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lints: ^3.0.0
  superclass_generator:
    path: ..
  test: ^1.24.0
