builders:
  superclass:
    import: "package:superclass_generator/superclass_generator.dart"
    builder_factories: [ "superclassBuilder" ]
    build_extensions: { ".dart": [ ".superclass.dart" ] }
    auto_apply: root_package
    build_to: source
    applies_builders: [ "source_gen|combining_builder" ]
    runs_before: [ "freezed|freezed", "json_serializable|json_serializable" ]
