name: superclass_generator
description: Generator for superclass package
version: 0.2.0
repository: https://github.com/exaby73/superclass/tree/main/packages/superclass_generator

environment:
  sdk: ^3.3.2

dependencies:
  analyzer: ^7.0.0
  build: ^2.4.2
  source_gen: ^2.0.0
  superclass: ^0.1.0

dev_dependencies:
  lint: ^2.3.0
  test: ^1.25.15
