name: superclass_generator
description: Generator for superclass package
version: 0.1.0
repository: https://github.com/exaby73/superclass/tree/main/packages/superclass_generator

environment:
  sdk: ^3.3.2

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  source_gen: ^1.5.0
  superclass: ^0.1.0

dev_dependencies:
  lint: ^2.3.0
  test: ^1.24.0
